### ISSUE TITLE
Can ink() method use the value to be redacted?

### ISSUE THREAD

**Issue by StyxOfDynamite** [mtownsend5512/array-redactor#3]
Just found your package, great work by the way 

Ive got a use case where I'd like to partially redact a value.

```
joe.bloggs@email.com => jo******@email.com
```

Just wondering if this was possible ?

**Comment by StyxOfDynamite** [comment]
Sorry looking in more depth I don't think this is doable as, should have read the source in more depth before opening.

**Comment by mtownsend5512** [comment]
Currently the ``ink`` method only does a full redaction. It would be possible if the class was modified to accept a closure. The closure would be executed for every redaction, though. I'd gladly accept a PR of this feature.

**Comment by StyxOfDynamite** [comment]
```
    /**
     * Set the value to replace redacted key values with, this can be a string or the return value of a closure.
     *
     * @param  mixed $ink What should replace the redacted data
     * @return object \Mtownsend\ArrayRedactor\ArrayRedactor
     */
    public function ink($ink = "[REDACTED]")
    {
        $this->ink = is_callable($ink) ? $ink() : $ink;
        return $this;
    }
```

Does this look OK ? Not made a submission before but this looks like it could add something to an already useful package.
